OrdererOrgs:
  - Name: Orderer
    Domain: defchain.local
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
        SANS: [localhost]
      - Hostname: orderer1
        SANS: [localhost]
      - Hostname: orderer2
        SANS: [localhost]
PeerOrgs:
  - Name: Police
    Domain: police.defchain.local
    EnableNodeOUs: true
    Template: { Count: 1, SANS: [localhost] }
    Users: { Count: 1 }
  - Name: RAB
    Domain: rab.defchain.local
    EnableNodeOUs: true
    Template: { Count: 1, SANS: [localhost] }
    Users: { Count: 1 }
  - Name: BGB
    Domain: bgb.defchain.local
    EnableNodeOUs: true
    Template: { Count: 1, SANS: [localhost] }
    Users: { Count: 1 }
  - Name: Customs
    Domain: customs.defchain.local
    EnableNodeOUs: true
    Template: { Count: 1, SANS: [localhost] }
    Users: { Count: 1 }
